### ISSUE TITLE
Guess file types for Scraping, Extension for Formats

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/metaeditor#24]
Add a field to the Formats model for a comma delimited list of file extensions ( So there can be more than one file extension for each format ) 

When scraping, set the file format for the entry from the first format that matches the file extension of the url.

**Comment by nmb10** [comment]
I think the `comma delimited list` is not good choice here because it will require complicated sql query or custom data structure while matching. Better choice is to create model (table) with extensions having relation to Format and db index over name of the extension. From client side view it will look like one input with comma separated extensions.

**Comment by ericbusboom** [comment]
That would be a better data model -- do that if you prefer to. 

> On Apr 7, 2015, at 12:20 AM, Kazbek <notifications@github.com> wrote:
> 
> I think the comma delimited list is not good choice here because it will require complicated sql query or custom data structure while matching. Better choice is to create model (table) with extensions having relation to Format and db index over name of the extension. From client side view it will look like one input with comma separated extensions.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

----------------------------------------------------------------------------------------------------------
Eric Busboom                                                                                (619) 363 2607        
eric@busboom.org                                                         http://www.busboom.org

**Comment by nmb10** [comment]
requires migration.
